# Site settings
title: "Grupo Linux para todos"
email: rmsaitam@gmail.com
description: "O objetivo do blog colaborativo é publicar posts dos possíveis problemas comuns e dúvidas dos membros no grupo https://t.me/LinuxParaTodos, assim basta enviar o link."
baseurl: "/"
url: "https://grupolinux.github.io"
twitter_username: "@blogcomputacao"
github_username:  "rmsaitam"
color_theme:  "#515151"
color_text:  "#fff"
language:  "pt"

collections:
    authors:
      output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

tipue_search:
  include:
    pages: true
    collections: [apples, oranges]